#encoding: utf-8
namespace :db do
  desc "Fill database with sample data"
  task populate: :environment do
    admin = User.create!(name: "Нестеров Александр", email: "alex19pov31@gmail.com", password: "19210289", password_confirmation: "19210289")
    admin.toggle!(:admin)
    users = {name: ["Renee Veum", "Kaylah Reichel Sr.", "Ms. Amelia Bradtke", "Josiane Conn", "Ms. Joshua Balistreri", "Miss Rosalee Nader", "Jodie Greenfelder", "Kennedi Ratke", "Orlo Keebler DDS", "Jerry Ferry", "Ebba Morissette", "Miss Liliane Larson", "Yessenia Hettinger", "Jalyn Greenholt", "Dr. Ernestina Zemlak", "Watson Ledner", "Mr. Kenyon Walsh", "Dorthy Smith", "Mrs. Mattie Beahan", "Miss Monte Hirthe", "Loyal Olson", "Mr. Caitlyn Gaylord", "Robin Hirthe", "Timothy O'Reilly", "Lamont Bode III", "Brennan Maggio", "Ms. Doyle Rodriguez", "Jacquelyn Baumbach Jr.", "Clifton Auer", "Enid Boehm", "Rubie Witting III", "Evans Rempel III", "Rasheed Lind", "Jackson Little", "Daija Lesch", "Joana Luettgen II", "Erich Marvin", "Rico Wolf", "Wilhelmine Balistreri", "Madeline Stamm", "Richie Grady", "Zita Gutkowski", "Donald Runolfsson", "Amaya Macejkovic", "Alexandrine Lockman", "Ms. Ignatius Morar", "Sabryna Lindgren Jr.", "Ms. Ines Huels", "Mrs. Henry Hilll", "Brody Kemmer", "Cordia Medhurst", "Maurine Senger", "Lorine Wintheiser", "Stephany Larkin PhD", "Ms. Camren Bechtelar", "Kip Senger II", "Ofelia Spinka", "Dr. Vicente Schroeder", "Ada Kertzmann", "Alfredo Fisher", "Leda Douglas II", "Terence Kuphal", "Timmothy Streich", "Dr. Dino Christiansen", "Alexandra Runte", "Kayli Mraz I", "Kailyn Pfeffer", "Leonie Jerde", "Howell Fay", "Jeffery Eichmann III", "Brice Nienow", "Hailie McCullough", "Mr. Arlo Russel", "Oren Miller", "Josue Walter MD", "Grace Lynch", "Mrs. Tobin Miller", "Asia Prosacco", "Joelle Hand", "Constance Wisoky Jr.", "Mohamed Prohaska", "Eino Bashirian", "Foster Jakubowski", "Emilie Gerhold", "Jerad Leannon", "Mekhi Von", "Christine Gulgowski", "Kory Gutkowski", "Ian Walsh", "Frances Renner", "Freddie Bergstrom", "Mr. Edyth Tremblay", "Aiden Morissette III", "Mr. Estelle Grant", "Jerrell Rice", "Marisa Littel", "Edison Mante", "Roberta Reilly", "Jaren Gottlieb"],
             email: ["abner@bechtelar.org", "karelle@ziemannmitchell.net", "benjamin@hagenes.name", "abdul@von.info", "kip@dickenshane.net", "wanda_kuvalis@casper.com", "zora.jewe@weimann.name", "felicity.hackett@robel.info", "hilbert@collier.info", "destin@bradtkelesch.com", "shirley_moriette@hauckmarks.net", "mattie@schmidt.info", "jillian@hamill.org", "salvador@blanda.info", "jeff@langworth.info", "sarah@bradtke.com", "luciano@langoshstrosin.biz", "chelsey_ko@corwin.com", "alicia@heidenreichpollich.org", "dameon_jewe@paucek.name", "aliyah@leuschke.org", "theresa@gusikowskilang.net", "casey_kilback@wisoky.net", "kayli.casper@robel.biz", "marlee@sporer.net", "jade@kling.net", "caden@dooley.net", "nicholaus_hilll@grahamweinat.org", "ruell@gerhold.biz", "jaqueline@wizacormier.biz", "vladimir@jewebrekke.com", "lynn_simonis@douglascasper.name", "ellen.considine@flatley.name", "justine@feest.net", "genesis_greenholt@abbott.biz", "rhea.miller@thompsonheaney.com", "wilber.swift@quigley.com", "kevon@smithkuhn.com", "chester@romaguera.biz", "adella@homenick.net", "fermin.lakin@collierstrosin.info", "celestine@morar.net", "reymundo@carroll.com", "raina_langworth@huelscarroll.net", "fannie@kertzmann.info", "salma_emmerich@sipes.info", "destinee_herman@yost.com", "dejon@sporer.info", "cara@hoppe.net", "stone@becker.com", "roberta@robel.name", "ro_moriette@kutch.name", "antonia@nikolaus.biz", "elya@hettinger.net", "daisha@joneshahn.com", "keaton_murphy@wiza.org", "mayra@erdman.name", "constantin.sauer@hammes.info", "federico@smitham.biz", "amely@kunde.com", "melany.hamill@hyattgislason.name", "frederick.heathcote@ryan.org", "zula@upton.net", "adeline@collins.info", "cedrick@mrazward.info", "keyshawn_dietrich@botsford.org", "trinity@rau.name", "lilian@sengerabbott.name", "virginia.schaden@bauchkshlerin.net", "robb@fritsch.com", "audreanne_halvorson@okunevaroberts.net", "delphia@gleichnerjacobson.name", "abelardo@turner.net", "jose_franecki@swift.info", "paolo@bailey.biz", "lorenz@wardmohr.info", "vicky.cummerata@gibson.name", "braulio.mosciski@rodriguez.biz", "enrico_reichel@larson.name", "audrey.raynor@lakin.info", "taya_feest@bogan.name", "esther_schowalter@simonis.biz", "anthony.olson@huels.info", "paxton_reichel@klein.com", "naomi.rogahn@gislasonrippin.net", "shanel.legros@johnson.biz", "gerhard_jakubowski@mcdermottgutkowski.biz", "chad@kovacek.org", "orrin.hintz@lockmanwintheiser.info", "jaylin@witting.org", "zelda_wiegand@terry.info", "estefania@reingermosciski.net", "lazaro_terry@volkmanrau.name", "laurianne@schroeder.net", "newell@lesch.com", "aron@monahantorp.biz", "palma@moen.info", "gustave@wilderman.org", "maritza.hodkiewicz@tremblay.com"]}
    #User.create!(name: "Example User", email: "example@railstutorial.org", password: "foobar", password_confirmation: "foobar")
    99.times do |n|
      User.create!(name: users[:name][n], email: users[:email][n], password: "foobar", password_confirmation: "foobar")
      #puts users[:email][n]
    end
  end
end